server:
  port: 8080

spring:
  application.name: project2
  output.ansi.enabled: always
  profiles.active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

    # H2 설정 (MySQL을 사용하지만, 테스트용으로 남겨둠)
    #    datasource:
    #      url: jdbc:h2:file:./db_project2;MODE=MySQL
    #      username: sa
    #      password:
    #      driver-class-name: org.h2.Driver

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            scope: name,profile,email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: ${PUBLIC_BASE_URL}/login/oauth2/code/naver
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope: https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/userinfo.email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: ${PUBLIC_BASE_URL}/login/oauth2/code/google
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.springframework.security: DEBUG

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    config-url: /v3/api-docs
    disable-swagger-default-url: true

custom:
  file:
    upload-dir: uploads/
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expire-seconds: 3600
    refresh-token-expire-seconds: 86400
  url:
    base-url: ${PUBLIC_BASE_URL}
    front-url: ${PUBLIC_FRONT_URL}
    domain: ${PUBLIC_DOMAIN}